In [171]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [172]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [173]:
print(x)

[['Mei' 44.0 72000.0]
 ['Juli' 87.0 50000.0]
 ['Juni' 30.0 44000.0]
 ['Mei' 78.0 69000.0]
 ['Juli' 40.0 nan]
 ['Juni' 25.0 50000.0]
 ['Mei' nan 62000.0]
 ['Juni' 48.0 69000.0]
 ['Juli' 60.0 89000.0]
 ['Mei' 37.0 37000.0]]


In [174]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [175]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [176]:
print(x)

[['Mei' 44.0 72000.0]
 ['Juli' 87.0 50000.0]
 ['Juni' 30.0 44000.0]
 ['Mei' 78.0 69000.0]
 ['Juli' 40.0 60222.22222222222]
 ['Juni' 25.0 50000.0]
 ['Mei' 49.888888888888886 62000.0]
 ['Juni' 48.0 69000.0]
 ['Juli' 60.0 89000.0]
 ['Mei' 37.0 37000.0]]


In [177]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [178]:
print(x)

[[0.0 0.0 1.0 44.0 72000.0]
 [1.0 0.0 0.0 87.0 50000.0]
 [0.0 1.0 0.0 30.0 44000.0]
 [0.0 0.0 1.0 78.0 69000.0]
 [1.0 0.0 0.0 40.0 60222.22222222222]
 [0.0 1.0 0.0 25.0 50000.0]
 [0.0 0.0 1.0 49.888888888888886 62000.0]
 [0.0 1.0 0.0 48.0 69000.0]
 [1.0 0.0 0.0 60.0 89000.0]
 [0.0 0.0 1.0 37.0 37000.0]]


In [179]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [180]:
print(y)

[1 1 0 0 1 1 0 1 0 1]


In [181]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [182]:
print(x_train)

[[0.0 0.0 1.0 49.888888888888886 62000.0]
 [1.0 0.0 0.0 40.0 60222.22222222222]
 [0.0 0.0 1.0 44.0 72000.0]
 [0.0 0.0 1.0 78.0 69000.0]
 [1.0 0.0 0.0 87.0 50000.0]
 [0.0 1.0 0.0 48.0 69000.0]
 [1.0 0.0 0.0 60.0 89000.0]
 [0.0 1.0 0.0 25.0 50000.0]]


In [183]:
print(x_test)

[[0.0 1.0 0.0 30.0 44000.0]
 [0.0 0.0 1.0 37.0 37000.0]]


In [184]:
print(y_train)

[0 1 1 0 1 1 0 1]


In [185]:
print(y_test)

[0 1]


In [186]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [187]:
print(x_train)

[[0.0 0.0 1.0 49.888888888888886 -0.264268289484419]
 [1.0 0.0 0.0 40.0 -0.41328300778400334]
 [0.0 0.0 1.0 44.0 0.5739395009507416]
 [0.0 0.0 1.0 78.0 0.3224771638201935]
 [1.0 0.0 0.0 87.0 -1.2701176380066117]
 [0.0 1.0 0.0 48.0 0.3224771638201935]
 [1.0 0.0 0.0 60.0 1.9988927446905147]
 [0.0 1.0 0.0 25.0 -1.2701176380066117]]


In [188]:
print(x_test)

[[0.0 1.0 0.0 30.0 -1.7730423122677081]
 [0.0 0.0 1.0 37.0 -2.3597877655723205]]
